# See all config options here https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build: "
    groups:
      python-production-updates:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      python-development-updates:
        dependency-type: "development"
        update-types:
          - "major"
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci: "
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      ci-updates:
        update-types:
          - "minor"
          - "patch"
          - "major"
