name: 'Integration Tests'
description: 'Runs the Integration tests '

inputs:
  TEST_API_KEY:
    description: 'The API_KEY for deepset Cloud'
    required: true
  API_URL:
    description: 'The API_URL for deepset Cloud'
    required: true

outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install Hatch
      shell: bash
      run: pip install hatch==${{ env.HATCH_VERSION }}
    # we are using the "automated-tests" organization with predefined users and workspaces
    - name: Run SDK Tests
      shell: bash
      run: |
        API_KEY=${{inputs.TEST_API_KEY}} API_URL=${{inputs.API_URL}}  hatch run test:integration
