name: "Integration Tests"
description: "Runs the Integration tests "

inputs:
  API_KEY:
    description: "The API_KEY for deepset"
    required: true
  API_URL:
    description: "The API_URL for deepset"
    required: true

outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: "3.10"
    - name: Install Dependencies
      shell: bash
      run: uv sync --group test
    # we are using the "automated-tests" organization with predefined users and workspaces
    - name: Run SDK Tests
      shell: bash
      run: |
        API_KEY=${{inputs.API_KEY}} API_URL=${{inputs.API_URL}} make tests-integration
