name: API Docs

on:
  push:
    branches:
      - main
      - feat/docsPage

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r docs/_pydoc/requirements.txt

      - name: Generate API docs
        env:
            # This is necessary to fetch the documentation categories
            # from Readme.io as we need them to associate the slug
            # in config files with their id.
            README_API_KEY: ${{ secrets.README_API_KEY }}
        run: ./.github/utils/pydoc-markdown.sh

      - run: pip install mkdocs-material mkdocstrings[python] mkdocs-mermaid2-plugin mkdocs-mike-plugin
      - run: mkdocs gh-deploy --force
