name: Compliance Checks

on:
  push:
    paths:
      - 'pyproject.toml'
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_ALERT_CHANNEL: "#dc-alerts"

jobs:
  check-license-compliance:
    name: Check license compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: "3.10"

      - name: Install prod dependencies
        run: |
          uv sync
          uv export --no-dev --no-hashes > requirements.txt

      - name: Create file with full dependency list
        run: |
          uv pip freeze > requirements-full.txt

      - name: Send license report to Fossa
        # This will collect all necessary information (mostly used dependencies) and send it to the Fossa API
        uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c # Use a specific version if locking is preferred
        with:
          api-key: ${{ secrets.FOSSA_LICENSE_SCAN_TOKEN }}

      - name: Check license compliance
        # This will poll the Fossa API until they have processed the information which we've sent in the previous step
        # and fail if Fossa found an issue with the licences of our dependencies.
        uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c # Use a specific version if locking is preferred
        with:
          api-key: ${{ secrets.FOSSA_LICENSE_SCAN_TOKEN }}
          run-tests: true

      - name: Send Slack notification if license check failed
        uses: act10ns/slack@d96404edccc6d6467fc7f8134a420c851b1e9054
        if: failure() && github.ref == 'refs/heads/main'
        with:
          status: ${{ job.status }}
          channel: ${{ env.SLACK_ALERT_CHANNEL }}
