name: Deploy to Test PyPi

on:
  pull_request:
    types:
      - labeled
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy-test:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.label.name == 'test-deploy') }}
    runs-on: ubuntu-latest
    environment: test
    env:
      pypi: ${{ vars.PYPI_URL }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true
          python-version: "3.10"
      - name: Build
        run: make build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          repository-url: ${{ env.pypi }}
