name: Deploy to Test PyPi

on:
  pull_request:
    types:
      - labeled
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy-test:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.label.name == 'test-deploy') }}
    runs-on: ubuntu-latest
    environment: test
    env:
      pypi: ${{ vars.PYPI_URL }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          python-version: "3.10"
      - name: Build
        run: make build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
        with:
          repository-url: ${{ env.pypi }}
